version: '3.7'
services:
  rabbitmq:
    image: bitnami/rabbitmq:3.9
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_USERNAME=test
      - RABBITMQ_PASSWORD=test

    restart: unless-stopped